#!/bin/bash -ex

LIBGODOT=~/work/pg/godot

MODE=release

pushd $LIBGODOT
./build_visionos $MODE visionos_simulator
./build_visionos $MODE visionos
cd bin
strip *.template_release.*.a
popd
bash -e make-libgodot.framework $LIBGODOT .. $MODE

OUTPUT=$LIBGODOT/../SwiftGodot/libgodot.xcframework

du -sh "$OUTPUT"

swift package compute-checksum "$OUTPUT"
