#!/bin/bash -ex

LIBGODOT=~/work/pg/godot

MODE=debug

pushd $LIBGODOT
./build_visionos $MODE visionos_simulator
./build_visionos $MODE visionos
popd
bash -e make-libgodot.framework $LIBGODOT .. $MODE


